version: "1"
services: 
    app:
        image: docker-101:1.0.0
        ports:
            - 8080:8080
        environment:
            - DATABASE_URL=postgres
        networks:
            - fullstack
    database:
        image: postgres:latest
        hostname: postgres
        ports:
            - 5432:5432
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=123456
        networks:
            - fullstack
networks:
    fullstack:
        driver: bridge
        
        

